export type ComfyUiFile = { filename: string; subfolder: string; type: string };
export function comfyUiLocalBaseUrl(value?: string): string;
export function minimaxH3LocalDimensions(ratio?: string): { width: number; height: number };
export function minimaxH3LocalFrameCount(duration?: number): number;
export function comfyUiMiniMaxH3Encoding(preset?: string): { preset: 'quality' | 'balanced' | 'compact' | 'quality10'; codec: 'h264'; bitDepth: 8 | 10; crf: number; saveVideoInputs: Record<string, string | number> };
export function videoContainerHasAudioTrack(buffer: Buffer | Uint8Array, extension?: string): boolean;
export function validateComfyUiMiniMaxH3Inputs<T extends { type: string; port?: string }>(inputs: T[]): T[];
export function mapComfyUiMiniMaxH3ReferencePrompt(prompt: string, references: Array<{ type: 'image' | 'video' | 'audio'; referenceToken?: string; hasAudioTrack?: boolean }>): string;
export function buildComfyUiMiniMaxH3Prompt(options: {
  prompt: string;
  ratio?: string;
  duration?: number;
  seed?: number;
  firstFrame?: string;
  lastFrame?: string;
  audioEnabled?: boolean;
  encodingPreset?: 'quality' | 'balanced' | 'compact' | 'quality10';
  samplingSteps?: 8 | 20 | 24 | 28;
  accelerationMode?: 'standard' | 'turbo' | 'reference8' | 'community8';
  filenamePrefix?: string;
  models?: { diffusion: string; textEncoder: string; videoVae: string; audioVae: string; turboDiffusionLora?: string };
}): Record<string, { class_type: string; inputs: Record<string, unknown> }>;
export function buildComfyUiMiniMaxH3ReferencePrompt(options: {
  prompt: string;
  ratio?: string;
  duration?: number;
  seed?: number;
  images?: string[];
  videos?: Array<string | { file: string; hasAudioTrack: boolean }>;
  audios?: string[];
  guides?: Array<{ type: 'image' | 'video' | 'audio'; file: string; frameIndex: number; hasAudioTrack?: boolean }>;
  refImageSize?: 'match' | 'max';
  audioEnabled?: boolean;
  encodingPreset?: 'quality' | 'balanced' | 'compact' | 'quality10';
  samplingSteps?: 8 | 20 | 24 | 28;
  accelerationMode?: 'standard' | 'turbo' | 'reference8' | 'community8';
  blockCache?: boolean;
  filenamePrefix?: string;
  models?: { referenceDiffusion: string; textEncoder: string; videoVae: string; audioVae: string; turboReferenceLora?: string; communityReferenceLora?: string };
}): Record<string, { class_type: string; inputs: Record<string, unknown> }>;
export function comfyUiHistoryOutput(entry: unknown): ComfyUiFile | null;
export function buildComfyUiMiniMaxH3FaceRefinePrompt(options: { video: string; duration?: number; seed?: number; audioEnabled?: boolean; encodingPreset?: 'quality' | 'balanced' | 'compact' | 'quality10'; filenamePrefix?: string; models?: { referenceDiffusion: string; textEncoder: string; videoVae: string; audioVae: string; turboReferenceLora: string } }): Record<string, { class_type: string; inputs: Record<string, unknown> }>;
export function comfyUiViewUrl(baseUrl: string, file: ComfyUiFile): string;
export type ComfyUiMiniMaxH3QueueStatus = { available: boolean; state: 'idle' | 'busy' | 'queued' | 'running' | 'offline'; concurrency: 1; running: number; queued: number; ahead: number; position: number; estimatedWaitSeconds: number; estimatedRunSeconds: number; baseUrl?: string; error?: string };
export function comfyUiMiniMaxH3QueueStatus(payload: unknown, options?: { promptId?: string; estimatedRunSeconds?: number }): ComfyUiMiniMaxH3QueueStatus;
export function inspectComfyUiMiniMaxH3(config?: { baseUrl?: string }, fetchImpl?: typeof fetch): Promise<{ available: boolean; baseUrl: string; error: string }>;
export function inspectComfyUiMiniMaxH3Queue(config?: { baseUrl?: string; estimatedRunSeconds?: number }, fetchImpl?: typeof fetch, promptId?: string): Promise<ComfyUiMiniMaxH3QueueStatus>;
export function createComfyUiMiniMaxH3Adapter(model: { id: string; config?: Record<string, unknown> }, fetchImpl?: typeof fetch): {
  kind: 'video';
  configured: true;
  run(job: Record<string, any>): Promise<{ outputs: Array<Record<string, any>>; usage: Record<string, any> }>;
};
