import type { PromptToken } from './prompt-token-library';

type Row = readonly [
  id: string,
  label: string,
  illustrious: string,
  sdxl?: string,
  natural?: string,
  aliases?: string[],
];

const group = (category: string, name: string, rows: readonly Row[]): PromptToken[] => rows.map(([id, label, illustrious, sdxl, natural, aliases]) => {
  const sdxlValue = sdxl || illustrious;
  return { id, scope: 'positive', category, group: name, label, values: { illustrious, sdxl: sdxlValue, natural: natural || sdxlValue }, aliases: aliases || [] };
});

/**
 * Extended production vocabulary kept separate from the core starter set so
 * the cascade remains data-driven. Every row has model-aware text rather than
 * being a display-only Chinese label.
 */
export const expandedPositivePromptTokens: PromptToken[] = [
  ...group('人物', '年龄气质', [
    ['age-young-adult', '青年', 'young adult', 'young adult character', 'a young adult character'],
    ['age-middle-aged', '中年', 'middle-aged', 'middle-aged character', 'a middle-aged character'],
    ['age-elderly', '老年', 'elderly', 'elderly character', 'an elderly character'],
    ['vibe-youthful', '青春感', 'youthful', 'youthful appearance', 'a youthful and lively appearance'],
    ['vibe-mature', '成熟感', 'mature', 'mature appearance', 'a composed mature appearance'],
    ['vibe-elegant', '优雅气质', 'elegant', 'elegant demeanor', 'an elegant and refined demeanor'],
    ['vibe-heroic', '英气', 'heroic demeanor', 'heroic demeanor', 'a bold heroic demeanor'],
    ['vibe-mysterious', '神秘气质', 'mysterious', 'mysterious demeanor', 'a mysterious and reserved demeanor'],
  ]),
  ...group('人物', '国家身份', [
    ['country-person-china', '中国人', 'Chinese person', 'Chinese person with natural individual features', 'a person from China with a natural contemporary appearance and individual facial features', ['中国人物', '华人', 'Chinese']],
    ['country-person-japan', '日本人', 'Japanese person', 'Japanese person with natural individual features', 'a person from Japan with a natural contemporary appearance and individual facial features', ['日本人物', 'Japanese']],
    ['country-person-korea', '韩国人', 'Korean person', 'South Korean person with natural individual features', 'a person from South Korea with a natural contemporary appearance and individual facial features', ['韩国人物', 'Korean']],
    ['country-person-usa', '美国人', 'American person', 'American person with natural individual features', 'a person from the United States with a natural contemporary appearance and individual facial features', ['美国人物', '美籍', 'American']],
    ['country-person-britain', '英国人', 'British person', 'British person with natural individual features', 'a person from the United Kingdom with a natural contemporary appearance and individual facial features', ['英国人物', 'British']],
    ['country-person-france', '法国人', 'French person', 'French person with natural individual features', 'a person from France with a natural contemporary appearance and individual facial features', ['法国人物', 'French']],
    ['country-person-germany', '德国人', 'German person', 'German person with natural individual features', 'a person from Germany with a natural contemporary appearance and individual facial features', ['德国人物', 'German']],
    ['country-person-italy', '意大利人', 'Italian person', 'Italian person with natural individual features', 'a person from Italy with a natural contemporary appearance and individual facial features', ['意大利人物', 'Italian']],
    ['country-person-spain', '西班牙人', 'Spanish person', 'Spanish person with natural individual features', 'a person from Spain with a natural contemporary appearance and individual facial features', ['西班牙人物', 'Spanish']],
    ['country-person-russia', '俄罗斯人', 'Russian person', 'Russian person with natural individual features', 'a person from Russia with a natural contemporary appearance and individual facial features', ['俄罗斯人物', 'Russian']],
    ['country-person-canada', '加拿大人', 'Canadian person', 'Canadian person with natural individual features', 'a person from Canada with a natural contemporary appearance and individual facial features', ['加拿大人物', 'Canadian']],
    ['country-person-mexico', '墨西哥人', 'Mexican person', 'Mexican person with natural individual features', 'a person from Mexico with a natural contemporary appearance and individual facial features', ['墨西哥人物', 'Mexican']],
    ['country-person-brazil', '巴西人', 'Brazilian person', 'Brazilian person with natural individual features', 'a person from Brazil with a natural contemporary appearance and individual facial features', ['巴西人物', 'Brazilian']],
    ['country-person-argentina', '阿根廷人', 'Argentine person', 'Argentine person with natural individual features', 'a person from Argentina with a natural contemporary appearance and individual facial features', ['阿根廷人物', 'Argentinian', 'Argentine']],
    ['country-person-india', '印度人', 'Indian person', 'Indian person with natural individual features', 'a person from India with a natural contemporary appearance and individual facial features', ['印度人物', 'Indian']],
    ['country-person-pakistan', '巴基斯坦人', 'Pakistani person', 'Pakistani person with natural individual features', 'a person from Pakistan with a natural contemporary appearance and individual facial features', ['巴基斯坦人物', 'Pakistani']],
    ['country-person-vietnam', '越南人', 'Vietnamese person', 'Vietnamese person with natural individual features', 'a person from Vietnam with a natural contemporary appearance and individual facial features', ['越南人物', 'Vietnamese']],
    ['country-person-thailand', '泰国人', 'Thai person', 'Thai person with natural individual features', 'a person from Thailand with a natural contemporary appearance and individual facial features', ['泰国人物', 'Thai']],
    ['country-person-philippines', '菲律宾人', 'Filipino person', 'Filipino person with natural individual features', 'a person from the Philippines with a natural contemporary appearance and individual facial features', ['菲律宾人物', 'Filipino']],
    ['country-person-indonesia', '印度尼西亚人', 'Indonesian person', 'Indonesian person with natural individual features', 'a person from Indonesia with a natural contemporary appearance and individual facial features', ['印尼人', '印度尼西亚人物', 'Indonesian']],
    ['country-person-turkey', '土耳其人', 'Turkish person', 'Turkish person with natural individual features', 'a person from Turkey with a natural contemporary appearance and individual facial features', ['土耳其人物', 'Turkish']],
    ['country-person-iran', '伊朗人', 'Iranian person', 'Iranian person with natural individual features', 'a person from Iran with a natural contemporary appearance and individual facial features', ['伊朗人物', '波斯人', 'Iranian', 'Persian']],
    ['country-person-egypt', '埃及人', 'Egyptian person', 'Egyptian person with natural individual features', 'a person from Egypt with a natural contemporary appearance and individual facial features', ['埃及人物', 'Egyptian']],
    ['country-person-nigeria', '尼日利亚人', 'Nigerian person', 'Nigerian person with natural individual features', 'a person from Nigeria with a natural contemporary appearance and individual facial features', ['尼日利亚人物', 'Nigerian']],
  ]),
  ...group('人物', '种族特征', [
    ['race-human', '人类', 'human', 'human character', 'a human character'],
    ['race-dark-elf', '暗夜精灵', 'dark elf', 'dark elf character', 'a dark elf character'],
    ['race-beastfolk', '兽人族', 'beastkin', 'beastfolk character', 'a fantasy beastfolk character'],
    ['race-cat-eared', '猫耳族', 'cat ears', 'cat-eared character', 'a character with cat-like ears'],
    ['race-fox-eared', '狐耳族', 'fox ears', 'fox-eared character', 'a character with fox-like ears'],
    ['race-dragonkin', '龙裔', 'dragonkin, dragon horns', 'dragonkin character', 'a dragonkin character with subtle draconic features'],
    ['race-fairy', '妖精族', 'fairy, fairy wings', 'fairy character', 'a delicate fairy character'],
    ['race-undead', '亡灵族', 'undead', 'undead fantasy character', 'an elegant undead fantasy character'],
  ]),
  ...group('人物', '头身比例', [
    ['proportion-2-head', '2头身', '2-head-tall chibi', 'two-head-tall chibi proportions', 'cute two-head-tall chibi proportions'],
    ['proportion-3-head', '3头身', '3-head-tall chibi', 'three-head-tall chibi proportions', 'stylized three-head-tall chibi proportions'],
    ['proportion-4-head', '4头身', '4-head-tall', 'four-head-tall stylized proportions', 'four-head-tall stylized proportions'],
    ['proportion-5-head', '5头身', '5-head-tall', 'five-head-tall proportions', 'five-head-tall game-character proportions'],
    ['proportion-6-head', '6头身', '6-head-tall', 'six-head-tall proportions', 'six-head-tall stylized proportions'],
    ['proportion-7-head', '7头身', '7-head-tall', 'seven-head-tall proportions', 'balanced seven-head-tall proportions'],
    ['proportion-8-head', '8头身', '8-head-tall', 'eight-head-tall heroic proportions', 'heroic eight-head-tall proportions'],
    ['proportion-long-legs', '长腿比例', 'long legs', 'long-legged proportions', 'elegant long-legged proportions'],
  ]),
  ...group('人物', '肤色特征', [
    ['skin-fair', '白皙肤色', 'fair skin', 'fair skin tone', 'a fair skin tone'],
    ['skin-warm', '暖色肤色', 'warm skin', 'warm skin tone', 'a warm natural skin tone'],
    ['skin-tan', '小麦肤色', 'tan skin', 'tanned skin', 'a healthy tanned skin tone'],
    ['skin-dark', '深色肤色', 'dark skin', 'deep skin tone', 'a rich deep skin tone'],
    ['skin-porcelain', '瓷白肌肤', 'porcelain skin', 'porcelain skin', 'smooth porcelain-like skin'],
    ['skin-sun-kissed', '阳光肤色', 'sun-kissed skin', 'sun-kissed skin', 'a sun-kissed skin tone'],
    ['skin-glowing', '微光肌肤', 'glowing skin', 'subtly glowing skin', 'skin with a subtle magical glow'],
    ['skin-fantasy-blue', '幻想蓝肤', 'blue skin', 'fantasy blue skin', 'fantasy blue-toned skin'],
  ]),
  ...group('人物', '发型细节', [
    ['hair-style-bob', '波波头', 'bob cut', 'bob haircut', 'a neat bob haircut'],
    ['hair-style-pixie', '精灵短发', 'pixie cut', 'short pixie cut', 'a stylish short pixie cut'],
    ['hair-style-hime', '姬发式', 'hime cut', 'hime-cut hairstyle', 'a traditional hime-cut hairstyle'],
    ['hair-style-bun', '盘发', 'hair bun', 'elegant hair bun', 'hair arranged in an elegant bun'],
    ['hair-style-double-bun', '双丸子头', 'double bun', 'double hair buns', 'hair styled in two buns'],
    ['hair-style-side-ponytail', '侧马尾', 'side ponytail', 'side ponytail', 'hair tied in a side ponytail'],
    ['hair-style-undercut', '渐层短发', 'undercut', 'modern undercut hairstyle', 'a modern undercut hairstyle'],
    ['hair-style-loose-strands', '碎发', 'loose hair strands', 'soft loose hair strands', 'soft loose strands framing the face'],
  ]),
  ...group('人物', '发色', [
    ['hair-color-brown', '棕发', 'brown hair', 'brown hair', 'brown hair'],
    ['hair-color-pink', '粉发', 'pink hair', 'pink hair', 'pink hair'],
    ['hair-color-purple', '紫发', 'purple hair', 'purple hair', 'purple hair'],
    ['hair-color-green', '绿发', 'green hair', 'green hair', 'green hair'],
    ['hair-color-silver', '银发', 'silver hair', 'silver hair', 'silver hair'],
    ['hair-color-ombre', '渐变发色', 'gradient hair', 'ombre hair color', 'hair with a controlled ombre gradient'],
    ['hair-color-two-tone', '双色发', 'two-tone hair', 'two-tone hair color', 'hair with a two-tone color design'],
    ['hair-color-highlight', '挑染', 'colored highlights', 'colored hair highlights', 'hair with distinct colored highlights'],
  ]),
  ...group('人物', '眼睛细节', [
    ['eyes-green', '绿眼', 'green eyes', 'green eyes', 'green eyes'],
    ['eyes-purple', '紫眼', 'purple eyes', 'purple eyes', 'purple eyes'],
    ['eyes-brown', '棕眼', 'brown eyes', 'brown eyes', 'brown eyes'],
    ['eyes-heterochromia', '异色瞳', 'heterochromia', 'heterochromatic eyes', 'eyes with two different iris colors'],
    ['eyes-glowing', '发光眼睛', 'glowing eyes', 'glowing eyes', 'subtly glowing eyes'],
    ['eyes-star-pupil', '星形瞳孔', 'star-shaped pupils', 'star-shaped pupils', 'stylized star-shaped pupils'],
    ['eyes-cat-pupil', '竖瞳', 'slit pupils', 'vertical slit pupils', 'vertical cat-like pupils'],
    ['eyes-soft-gaze', '温柔眼神', 'gentle eyes', 'gentle eyes', 'a soft and gentle gaze'],
  ]),

  ...group('服饰', '上装', [
    ['top-shirt', '衬衫', 'shirt', 'tailored shirt', 'a tailored shirt'],
    ['top-blouse', '女式衬衣', 'blouse', 'elegant blouse', 'an elegant blouse'],
    ['top-tunic', '束腰长衣', 'tunic', 'fitted fantasy tunic', 'a fitted fantasy tunic'],
    ['top-crop-jacket', '短款夹克', 'cropped jacket', 'cropped jacket', 'a fitted cropped jacket'],
    ['top-sweater', '针织上衣', 'sweater', 'knitted sweater', 'a textured knitted sweater'],
    ['top-hoodie', '连帽衫', 'hoodie', 'modern hoodie', 'a modern layered hoodie'],
    ['top-bodice', '紧身胸衣', 'corset bodice', 'structured corset bodice', 'a structured decorative corset bodice'],
    ['top-tabard', '骑士罩袍', 'tabard', 'knight tabard', 'a heraldic knight tabard'],
  ]),
  ...group('服饰', '裙装', [
    ['bottom-long-skirt', '长裙', 'long skirt', 'flowing long skirt', 'a flowing long skirt'],
    ['bottom-pleated-skirt', '百褶裙', 'pleated skirt', 'pleated skirt', 'a structured pleated skirt'],
    ['bottom-armored-skirt', '甲裙', 'armored skirt', 'layered armored skirt', 'a layered armored battle skirt'],
    ['bottom-slit-skirt', '开衩裙', 'slit skirt', 'side-slit skirt', 'an elegant side-slit skirt'],
  ]),
  ...group('服饰', '下装', [
    ['bottom-pants', '长裤', 'pants', 'tailored trousers', 'tailored trousers'],
    ['bottom-shorts', '短裤', 'shorts', 'fitted shorts', 'fitted practical shorts'],
    ['bottom-hakama', '袴裤', 'hakama', 'traditional hakama trousers', 'traditional hakama trousers'],
    ['bottom-cargo', '工装裤', 'cargo pants', 'utility cargo pants', 'practical utility cargo pants'],
  ]),
  ...group('服饰', '外套', [
    ['outer-long-coat', '长风衣', 'long coat', 'long tailored coat', 'a long tailored coat'],
    ['outer-trench', '风衣', 'trench coat', 'trench coat', 'a structured trench coat'],
    ['outer-fur-cape', '毛领斗篷', 'fur-trimmed cape', 'fur-trimmed cape', 'a cape with a fur-trimmed collar'],
    ['outer-hooded-cloak', '兜帽斗篷', 'hooded cloak', 'hooded fantasy cloak', 'a hooded fantasy cloak'],
    ['outer-bolero', '短外套', 'bolero jacket', 'short bolero jacket', 'a short decorative bolero jacket'],
    ['outer-kimono-coat', '羽织', 'haori', 'traditional haori coat', 'a traditional haori coat'],
    ['outer-armored-coat', '战甲大衣', 'armored coat', 'armored military coat', 'a long military coat reinforced with armor'],
    ['outer-transparent', '薄纱外披', 'sheer outer robe', 'sheer layered outer robe', 'a translucent layered outer robe'],
  ]),
  ...group('服饰', '鞋袜', [
    ['footwear-ankle-boots', '短靴', 'ankle boots', 'ankle boots', 'fitted ankle boots'],
    ['footwear-thigh-boots', '过膝靴', 'thighhigh boots', 'over-the-knee boots', 'over-the-knee boots'],
    ['footwear-armored-boots', '战甲靴', 'armored boots', 'armored battle boots', 'reinforced armored battle boots'],
    ['footwear-sandals', '绑带凉鞋', 'strappy sandals', 'strappy sandals', 'elegant strappy sandals'],
    ['footwear-platform', '厚底鞋', 'platform shoes', 'platform shoes', 'stylized platform shoes'],
    ['footwear-stockings', '贴腿长袜', 'fitted thighhigh stockings', 'long fitted stockings', 'long fitted stockings'],
    ['footwear-tabi', '足袋', 'tabi', 'traditional tabi socks', 'traditional tabi socks'],
    ['footwear-barefoot', '赤足', 'barefoot', 'bare feet', 'bare feet'],
  ]),
  ...group('服饰', '头饰', [
    ['headwear-crown', '宝石王冠', 'jeweled crown', 'ornate jeweled crown', 'an ornate jeweled royal crown'],
    ['headwear-tiara', '额冠', 'tiara', 'delicate tiara', 'a delicate jeweled tiara'],
    ['headwear-hood', '布质兜帽', 'fabric hood', 'layered fabric hood', 'a layered fabric hood'],
    ['headwear-beret', '贝雷帽', 'beret', 'stylish beret', 'a stylish beret'],
    ['headwear-wide-hat', '宽檐帽', 'wide-brimmed hat', 'wide-brimmed hat', 'a dramatic wide-brimmed hat'],
    ['headwear-witch-hat', '魔女帽', 'witch hat', 'fantasy witch hat', 'a detailed fantasy witch hat'],
    ['headwear-halo', '光环', 'halo', 'glowing halo', 'a luminous halo'],
    ['headwear-horns', '装饰角冠', 'horned headdress', 'horned ceremonial headdress', 'a ceremonial horned headdress'],
  ]),
  ...group('服饰', '首饰', [
    ['jewelry-necklace', '垂饰项链', 'pendant necklace', 'ornate pendant necklace', 'an ornate pendant necklace'],
    ['jewelry-choker', '颈圈', 'choker', 'decorative choker', 'a decorative choker'],
    ['jewelry-earrings', '耳坠', 'dangling earrings', 'dangling earrings', 'delicate dangling earrings'],
    ['jewelry-bracelet', '手镯', 'bracelet', 'ornate bracelet', 'an ornate bracelet'],
    ['jewelry-brooch', '胸针', 'brooch', 'jeweled brooch', 'a jeweled brooch'],
    ['jewelry-body-chain', '链饰', 'body chain', 'decorative body chain', 'a tasteful decorative body chain'],
    ['jewelry-talisman', '护符', 'talisman', 'mystic talisman jewelry', 'a mystic talisman worn as jewelry'],
    ['jewelry-pearls', '珍珠饰品', 'pearl jewelry', 'pearl jewelry', 'refined pearl jewelry'],
  ]),
  ...group('服饰', '护甲结构', [
    ['armor-plate', '板甲', 'plate armor', 'full plate armor', 'structured full plate armor'],
    ['armor-scale', '鳞甲', 'scale armor', 'layered scale armor', 'layered scale armor'],
    ['armor-chainmail', '锁子甲', 'chainmail', 'chainmail armor', 'finely linked chainmail armor'],
    ['armor-lamellar', '札甲', 'lamellar armor', 'lamellar armor', 'layered lamellar armor'],
    ['armor-light', '轻甲', 'light armor', 'lightweight fantasy armor', 'lightweight fantasy armor'],
    ['armor-shoulder', '装饰肩甲', 'ornate pauldrons', 'ornate shoulder armor', 'ornate shoulder armor'],
    ['armor-gauntlets', '臂铠', 'armored gauntlets', 'armored gauntlets', 'reinforced armored gauntlets'],
    ['armor-greaves', '腿甲', 'greaves', 'armored greaves', 'reinforced armored greaves'],
  ]),
  ...group('服饰', '纹样', [
    ['pattern-floral', '花卉纹样', 'floral pattern', 'floral textile pattern', 'a refined floral textile pattern'],
    ['pattern-cloud', '云纹', 'cloud pattern', 'traditional cloud pattern', 'a traditional flowing cloud motif'],
    ['pattern-dragon', '龙纹', 'dragon pattern', 'dragon motif', 'an ornate dragon motif'],
    ['pattern-phoenix', '凤纹', 'phoenix pattern', 'phoenix motif', 'an elegant phoenix motif'],
    ['pattern-geometric', '几何纹样', 'geometric pattern', 'geometric textile pattern', 'a clean geometric textile pattern'],
    ['pattern-runes', '符文纹样', 'rune pattern', 'glowing rune pattern', 'a subtle glowing rune pattern'],
    ['pattern-heraldic', '纹章图案', 'heraldic pattern', 'heraldic crest pattern', 'a heraldic crest motif'],
    ['pattern-embroidery', '精细刺绣', 'intricate embroidery', 'intricate embroidery', 'intricate hand-embroidered details'],
  ]),

  ...group('表情动作', '表情', [
    ['emotion-joyful', '喜悦', 'joyful', 'bright joyful facial expression', 'a bright and joyful emotional tone'],
    ['emotion-sad', '悲痛', 'grief-stricken', 'grief-stricken expression', 'a visibly grief-stricken emotional tone'],
    ['emotion-angry', '怒意', 'furious', 'furious expression', 'an intense furious emotion'],
    ['emotion-surprised', '惊愕', 'wide-eyed surprise', 'wide-eyed surprised expression', 'a wide-eyed surprised reaction'],
    ['emotion-shy', '羞怯', 'bashful', 'bashful expression', 'a bashful and reserved emotion'],
    ['emotion-determined', '决意', 'resolute', 'resolute expression', 'a firmly resolute emotion'],
    ['emotion-melancholy', '忧郁', 'melancholic', 'melancholic expression', 'a quiet melancholic mood'],
    ['emotion-playful', '俏皮', 'playful', 'playful expression', 'a playful mischievous mood'],
  ]),
  ...group('表情动作', '站姿', [
    ['stance-relaxed', '放松站立', 'relaxed standing', 'relaxed standing pose', 'standing in a relaxed pose'],
    ['stance-contrapposto', '重心站姿', 'contrapposto', 'contrapposto stance', 'standing in a natural contrapposto stance'],
    ['stance-hands-hips', '双手叉腰', 'both hands on hips', 'hands-on-hips standing pose', 'standing with both hands on the hips'],
    ['stance-crossed-arms', '抱臂站立', 'standing with crossed arms', 'upright crossed-arm stance', 'standing upright with both arms crossed'],
    ['stance-one-leg-forward', '单腿前伸', 'one leg forward', 'one-leg-forward stance', 'standing with one leg placed forward'],
    ['stance-back-to-back', '背靠背', 'back-to-back', 'back-to-back pose', 'two characters standing back to back'],
    ['stance-guard', '防守架势', 'defensive stance', 'defensive standing pose', 'standing in a defensive stance'],
    ['stance-victory', '胜利站姿', 'victory pose', 'heroic victory stance', 'standing in a heroic victory pose'],
  ]),
  ...group('表情动作', '坐姿', [
    ['pose-sitting-chair', '坐在椅子上', 'sitting on chair', 'seated on a chair', 'sitting naturally on a chair'],
    ['pose-sitting-ground', '席地而坐', 'sitting on ground', 'seated on the ground', 'sitting on the ground'],
    ['pose-perched', '高处坐姿', 'perched', 'perched on an edge', 'sitting on the edge of a raised surface'],
  ]),
  ...group('表情动作', '跪蹲', [
    ['pose-kneeling-composed', '端正跪姿', 'formal kneeling', 'composed kneeling pose', 'kneeling in a composed formal pose'],
    ['pose-crouching', '蹲姿', 'crouching', 'crouching pose', 'crouching in a balanced pose'],
  ]),
  ...group('表情动作', '躺卧', [
    ['pose-reclining', '斜倚', 'reclining', 'reclining pose', 'reclining against a surface'],
    ['pose-lying-back', '仰卧', 'lying on back', 'lying on the back', 'lying on the back'],
    ['pose-lying-side', '侧卧', 'lying on side', 'lying on the side', 'lying on one side'],
  ]),
  ...group('表情动作', '战斗动作', [
    ['action-sword-swing', '劈砍', 'overhead sword slash', 'forceful overhead sword slash', 'performing a forceful overhead sword slash'],
    ['action-sword-thrust', '突刺', 'sword thrust', 'forward sword thrust', 'performing a forward sword thrust'],
    ['action-bow-draw', '拉弓', 'drawing bow', 'drawing a bow', 'drawing a bow and aiming'],
    ['action-spell-cast', '释放法术', 'spellcasting with extended hand', 'casting a spell with an extended hand', 'casting a spell with an extended hand'],
    ['action-shield-block', '举盾格挡', 'shield block', 'blocking with a shield', 'blocking an attack with a shield'],
    ['action-dodge', '闪避', 'dodging', 'dynamic dodge', 'performing a dynamic evasive movement'],
    ['action-leap-attack', '跃起攻击', 'jumping attack', 'leaping attack pose', 'attacking while leaping through the air'],
    ['action-duel', '近身对决', 'dueling', 'close-quarters duel', 'two fighters engaged in a close duel'],
  ]),
  ...group('表情动作', '日常动作', [
    ['daily-reading', '阅读', 'reading', 'reading a book', 'quietly reading a book'],
    ['daily-writing', '书写', 'writing', 'writing at a desk', 'writing carefully at a desk'],
    ['daily-drinking-tea', '饮茶', 'drinking tea', 'drinking tea', 'gracefully drinking tea'],
    ['daily-cooking', '料理', 'cooking', 'cooking food', 'preparing food in a kitchen'],
  ]),
  ...group('表情动作', '人物互动', [
    ['daily-conversation', '交谈', 'talking', 'characters talking', 'characters engaged in conversation'],
    ['daily-holding-hands', '牵手', 'holding hands', 'holding hands', 'two characters holding hands'],
    ['daily-hug', '拥抱', 'hugging', 'gentle embrace', 'characters sharing a gentle embrace'],
    ['daily-gift', '递出礼物', 'giving gift', 'offering a gift', 'one character offering a gift'],
  ]),
  ...group('表情动作', '行走跑跳', [
    ['motion-running', '疾跑', 'dynamic running', 'dynamic running pose', 'running with clear forward momentum'],
    ['motion-sprinting', '冲刺', 'sprinting', 'full-speed sprint', 'sprinting at full speed'],
    ['motion-jumping', '腾跃', 'leaping through air', 'dynamic leaping pose', 'leaping dynamically through the air'],
  ]),
  ...group('表情动作', '舞蹈运动', [
    ['motion-spinning', '旋转', 'spinning', 'spinning motion', 'turning in a flowing spinning motion'],
    ['motion-dance-elegant', '优雅舞姿', 'elegant dancing', 'elegant dance pose', 'performing an elegant dance movement'],
    ['motion-ballet', '芭蕾动作', 'ballet', 'ballet pose', 'performing a controlled ballet pose'],
    ['motion-martial-arts', '武术动作', 'martial arts', 'martial-arts pose', 'performing a precise martial-arts movement'],
  ]),
  ...group('表情动作', '身体姿态', [
    ['motion-floating', '空中漂浮', 'weightless floating', 'weightless floating pose', 'floating weightlessly in the air'],
  ]),

  ...group('构图', '画幅布局', [
    ['layout-vertical-poster', '竖版海报', 'vertical composition', 'vertical poster composition', 'a vertical poster composition'],
    ['layout-horizontal-cinematic', '横版电影构图', 'horizontal composition', 'cinematic horizontal composition', 'a cinematic horizontal composition'],
    ['layout-square-card', '方形卡面', 'square composition', 'square card composition', 'a square card-art composition'],
    ['layout-subject-left', '主体居左', 'subject on left', 'subject placed on the left', 'the subject composed on the left side'],
    ['layout-subject-right', '主体居右', 'subject on right', 'subject placed on the right', 'the subject composed on the right side'],
    ['layout-top-heavy', '上部视觉重心', 'top-heavy composition', 'upper-weighted composition', 'a composition weighted toward the upper frame'],
    ['layout-bottom-heavy', '下部视觉重心', 'bottom-heavy composition', 'lower-weighted composition', 'a composition grounded in the lower frame'],
    ['layout-diagonal', '强对角线', 'strong diagonal flow', 'emphatic diagonal frame layout', 'an emphatic diagonal frame layout'],
  ]),
  ...group('构图', '视觉引导', [
    ['guide-leading-lines', '引导线', 'leading lines', 'strong leading lines', 'clear leading lines toward the subject'],
    ['guide-frame-within-frame', '框中框', 'nested frame composition', 'nested frame-within-frame layout', 'a nested frame-within-frame visual layout'],
    ['guide-foreground-framing', '前景遮挡', 'foreground occlusion', 'foreground elements partially occluding the subject', 'foreground elements partially overlapping and framing the subject'],
    ['guide-radial', '放射构图', 'radial composition', 'radial visual flow', 'radial visual flow centered on the subject'],
    ['guide-s-curve', 'S形动线', 'S-curve composition', 'S-curve visual flow', 'an S-shaped visual path through the image'],
    ['guide-triangle', '稳定三角布局', 'stable triangular layout', 'stable triangular subject arrangement', 'a stable triangular arrangement of visual subjects'],
    ['guide-golden-ratio', '黄金分割', 'golden ratio composition', 'golden-ratio composition', 'a composition guided by the golden ratio'],
    ['guide-eye-path', '视线动线', 'visual hierarchy', 'clear visual hierarchy', 'a clear eye path and visual hierarchy'],
  ]),
  ...group('构图', '景深层次', [
    ['depth-foreground', '突出前景', 'detailed foreground', 'detailed foreground layer', 'a clearly defined foreground layer'],
    ['depth-midground', '突出中景', 'detailed midground', 'detailed midground layer', 'a clearly defined midground layer'],
    ['depth-background', '远景层次', 'layered background', 'layered distant background', 'a layered distant background'],
    ['depth-shallow', '浅景深', 'shallow depth of field', 'shallow depth of field', 'a shallow depth of field'],
    ['depth-deep', '大景深', 'deep focus', 'deep depth of field', 'deep focus across the whole scene'],
    ['depth-aerial', '空气透视', 'aerial perspective', 'atmospheric perspective', 'strong atmospheric perspective'],
    ['depth-overlap', '遮挡层次', 'overlapping forms', 'layered overlapping forms', 'depth created through overlapping forms'],
    ['depth-scale', '尺度对比', 'scale contrast', 'strong scale contrast', 'depth emphasized by strong scale contrast'],
  ]),

  ...group('生物', '动物', [
    ['animal-cat', '猫', 'cat', 'cat', 'a cat'],
    ['animal-dog', '狗', 'dog', 'dog', 'a dog'],
    ['animal-wolf', '狼', 'wolf', 'wolf', 'a wolf'],
    ['animal-fox', '狐狸', 'fox', 'fox', 'a fox'],
    ['animal-rabbit', '兔子', 'rabbit', 'rabbit', 'a rabbit'],
    ['animal-deer', '鹿', 'deer', 'deer', 'a deer'],
    ['animal-horse', '马', 'horse', 'horse', 'a horse'],
    ['animal-eagle', '鹰', 'eagle', 'eagle', 'an eagle'],
  ]),
  ...group('生物', '幻想生物', [
    ['creature-dragon', '巨龙', 'dragon', 'majestic fantasy dragon', 'a majestic fantasy dragon'],
    ['creature-phoenix', '凤凰', 'phoenix', 'luminous phoenix', 'a luminous phoenix'],
    ['creature-unicorn', '独角兽', 'unicorn', 'fantasy unicorn', 'a graceful fantasy unicorn'],
    ['creature-griffin', '狮鹫', 'griffin', 'fantasy griffin', 'a powerful fantasy griffin'],
    ['creature-kirin', '麒麟', 'qilin', 'mythical qilin', 'a mythical qilin'],
    ['creature-mermaid', '人鱼', 'mermaid', 'fantasy merfolk', 'an elegant fantasy merfolk character'],
    ['creature-centaur', '半人马', 'centaur', 'fantasy centaur', 'a fantasy centaur'],
    ['creature-spirit', '元素精灵', 'elemental spirit', 'elemental spirit creature', 'a small elemental spirit creature'],
  ]),
  ...group('生物', '怪物', [
    ['monster-slime', '史莱姆', 'slime monster', 'stylized slime creature', 'a stylized slime creature'],
    ['monster-goblin', '哥布林', 'goblin', 'fantasy goblin', 'a fantasy goblin'],
    ['monster-orc', '兽人', 'orc', 'armored orc', 'an armored fantasy orc'],
    ['monster-troll', '巨魔', 'troll', 'massive troll', 'a massive fantasy troll'],
    ['monster-golem', '魔像', 'golem', 'ancient stone golem', 'an ancient stone golem'],
    ['monster-skeleton', '骷髅战士', 'skeleton warrior', 'skeleton warrior', 'an armored skeleton warrior'],
    ['monster-wraith', '幽灵', 'wraith', 'spectral wraith', 'a spectral fantasy wraith'],
    ['monster-chimera', '奇美拉', 'chimera', 'fantasy chimera', 'a hybrid fantasy chimera'],
  ]),
  ...group('生物', '宠物坐骑', [
    ['companion-familiar', '魔法使魔', 'familiar', 'small magical familiar', 'a small magical familiar companion'],
    ['companion-fairy', '精灵伙伴', 'fairy companion', 'tiny fairy companion', 'a tiny fairy companion'],
    ['companion-robot', '机械宠物', 'robot pet', 'small robotic companion', 'a small robotic companion'],
    ['companion-spirit-fox', '灵狐', 'spirit fox', 'glowing spirit fox', 'a glowing spirit fox companion'],
    ['mount-warhorse', '战马', 'warhorse', 'armored warhorse', 'an armored warhorse'],
    ['mount-wyvern', '飞龙坐骑', 'wyvern mount', 'rideable wyvern', 'a rideable fantasy wyvern'],
    ['mount-wolf', '巨狼坐骑', 'giant wolf mount', 'giant wolf mount', 'a giant wolf used as a mount'],
    ['mount-mechanical', '机械坐骑', 'mechanical mount', 'fantasy mechanical mount', 'a detailed fantasy mechanical mount'],
  ]),

  ...group('建筑', '中式建筑', [
    ['arch-chinese-palace', '中式宫殿', 'Chinese palace', 'grand Chinese palace', 'a grand traditional Chinese palace'],
    ['arch-chinese-pavilion', '亭台', 'Chinese pavilion', 'traditional Chinese pavilion', 'a traditional Chinese pavilion'],
    ['arch-chinese-temple', '古寺', 'Chinese temple', 'ancient Chinese temple', 'an ancient Chinese temple'],
    ['arch-chinese-garden', '园林', 'Chinese garden', 'classical Chinese garden', 'a classical Chinese garden'],
    ['arch-chinese-gate', '山门', 'traditional gate', 'monumental Chinese gate', 'a monumental traditional Chinese gate'],
    ['arch-chinese-town', '古镇', 'ancient Chinese town', 'historic Chinese water town', 'a historic Chinese water town'],
    ['arch-chinese-wall', '城墙', 'Chinese city wall', 'ancient fortified city wall', 'an ancient fortified city wall'],
    ['arch-chinese-bridge', '廊桥', 'covered bridge', 'traditional covered bridge', 'a traditional covered wooden bridge'],
  ]),
  ...group('建筑', '欧式建筑', [
    ['arch-europe-castle', '欧洲城堡', 'European castle', 'medieval European castle', 'a grand medieval European castle'],
    ['arch-gothic-cathedral', '哥特教堂', 'Gothic cathedral', 'Gothic cathedral', 'a towering Gothic cathedral'],
    ['arch-baroque-palace', '巴洛克宫殿', 'baroque palace', 'ornate Baroque palace', 'an ornate Baroque palace'],
    ['arch-renaissance-courtyard', '文艺复兴庭院', 'Renaissance courtyard', 'Renaissance courtyard', 'a refined Renaissance courtyard'],
    ['arch-medieval-village', '中世纪村庄', 'medieval village', 'medieval European village', 'a lively medieval European village'],
    ['arch-stone-keep', '石砌堡垒', 'stone keep', 'fortified stone keep', 'a fortified stone keep'],
    ['arch-clocktower', '钟楼', 'clock tower', 'historic clock tower', 'a tall historic clock tower'],
    ['arch-europe-manor', '庄园', 'European manor', 'historic country manor', 'a historic European country manor'],
  ]),
  ...group('建筑', '现代建筑', [
    ['arch-modern-villa', '现代别墅', 'modern villa', 'minimal modern villa', 'a minimal modern villa'],
    ['arch-skyscraper', '摩天楼', 'skyscraper', 'glass skyscraper', 'a tall glass skyscraper'],
    ['arch-office', '办公空间', 'modern office', 'contemporary office interior', 'a contemporary office interior'],
    ['arch-shopping-mall', '商业中心', 'shopping mall', 'modern shopping center', 'a modern shopping center'],
    ['arch-subway', '地铁站', 'subway station', 'modern subway station', 'a modern urban subway station'],
    ['arch-airport', '机场大厅', 'airport terminal', 'large airport terminal', 'a spacious airport terminal'],
    ['arch-industrial-loft', '工业阁楼', 'industrial loft', 'industrial loft interior', 'a spacious industrial loft interior'],
    ['arch-brutalist', '粗野主义建筑', 'brutalist architecture', 'monumental brutalist architecture', 'monumental brutalist architecture'],
  ]),
  ...group('建筑', '科幻建筑', [
    ['arch-space-station', '空间站', 'space station', 'vast orbital space station', 'a vast orbital space station'],
    ['arch-cyber-city', '赛博城市', 'cyberpunk city', 'dense cyberpunk megacity', 'a dense neon cyberpunk megacity'],
    ['arch-future-tower', '未来高塔', 'futuristic tower', 'futuristic megastructure tower', 'a towering futuristic megastructure'],
    ['arch-lunar-base', '月球基地', 'lunar base', 'advanced lunar colony', 'an advanced lunar colony'],
    ['arch-underwater-city', '海底城市', 'underwater city', 'futuristic underwater city', 'a futuristic city beneath the ocean'],
    ['arch-alien-ruin', '外星遗迹', 'alien ruins', 'ancient alien megastructure', 'an ancient alien megastructure'],
    ['arch-holographic-interior', '全息大厅', 'holographic hall', 'holographic control hall', 'a futuristic holographic control hall'],
    ['arch-floating-city', '浮空城', 'floating city', 'vast floating city', 'a vast city floating above the clouds'],
  ]),
  ...group('建筑', '室内空间', [
    ['interior-throne-room', '王座大厅', 'throne room', 'grand throne room interior', 'a grand royal throne room'],
    ['interior-library', '大型图书馆', 'grand library', 'vast historic library', 'a vast historic library interior'],
    ['interior-tavern', '酒馆', 'fantasy tavern', 'warm fantasy tavern interior', 'a warm lively fantasy tavern'],
    ['interior-workshop', '工坊', 'workshop', 'detailed artisan workshop', 'a detailed artisan workshop'],
    ['interior-laboratory', '实验室', 'laboratory', 'advanced research laboratory', 'an advanced research laboratory'],
    ['interior-bedroom', '卧室', 'bedroom interior', 'cozy bedroom interior', 'a cozy detailed bedroom'],
    ['interior-ballroom', '宴会厅', 'ballroom', 'ornate grand ballroom', 'an ornate grand ballroom'],
    ['interior-corridor', '长廊', 'long corridor', 'dramatic architectural corridor', 'a dramatic long architectural corridor'],
  ]),

  ...group('自然', '地貌', [
    ['terrain-mountain', '高山', 'mountain', 'towering mountain landscape', 'a landscape of towering mountains'],
    ['terrain-canyon', '峡谷', 'canyon', 'vast rocky canyon', 'a vast rocky canyon'],
    ['terrain-desert', '沙漠', 'desert', 'expansive desert dunes', 'expansive desert dunes'],
    ['terrain-grassland', '草原', 'grassland', 'open green grassland', 'a wide open green grassland'],
    ['terrain-tundra', '冻原', 'tundra', 'icy tundra landscape', 'an icy tundra landscape'],
    ['terrain-volcano', '火山', 'volcano', 'active volcanic landscape', 'an active volcanic landscape'],
    ['terrain-cave', '洞穴', 'cave', 'vast natural cave', 'a vast natural cave interior'],
    ['terrain-floating-island', '浮岛', 'floating island', 'floating island landscape', 'islands floating high in the sky'],
  ]),
  ...group('自然', '植被', [
    ['flora-bamboo', '竹林', 'bamboo forest', 'dense bamboo grove', 'a dense bamboo grove'],
    ['flora-cherry', '樱花林', 'cherry blossoms', 'cherry-blossom grove', 'a grove filled with blooming cherry trees'],
    ['flora-maple', '枫树林', 'maple forest', 'red maple forest', 'a forest of red maple trees'],
    ['flora-pine', '松林', 'pine forest', 'misty pine forest', 'a misty pine forest'],
    ['flora-flower-field', '花海', 'flower field', 'vast field of flowers', 'a vast field filled with flowers'],
    ['flora-giant-tree', '巨树', 'giant tree', 'ancient colossal tree', 'an ancient colossal tree'],
    ['flora-vines', '藤蔓', 'vines', 'lush climbing vines', 'lush vines climbing across surfaces'],
    ['flora-glowing-plants', '发光植物', 'glowing plants', 'bioluminescent plants', 'bioluminescent fantasy plants'],
  ]),
  ...group('自然', '水体', [
    ['water-ocean', '海洋', 'ocean', 'vast ocean', 'a vast open ocean'],
    ['water-lake', '湖泊', 'lake', 'calm reflective lake', 'a calm reflective lake'],
    ['water-river', '河流', 'river', 'winding river', 'a winding natural river'],
    ['water-waterfall', '瀑布', 'waterfall', 'towering waterfall', 'a towering waterfall'],
    ['water-stream', '溪流', 'stream', 'clear forest stream', 'a clear stream through the forest'],
    ['water-hot-spring', '温泉', 'hot spring', 'natural hot spring', 'a steaming natural hot spring'],
    ['water-underwater', '水下世界', 'underwater', 'underwater environment', 'a vivid underwater environment'],
    ['water-ice-lake', '冰湖', 'frozen lake', 'frozen reflective lake', 'a frozen reflective lake'],
  ]),
  ...group('自然', '天空天象', [
    ['sky-clear-blue', '晴朗蓝天', 'blue sky', 'clear blue sky', 'a clear blue sky'],
    ['sky-cloud-sea', '云海', 'sea of clouds', 'vast sea of clouds', 'a vast sea of clouds'],
    ['sky-starry', '繁星夜空', 'starry sky', 'dense starry sky', 'a night sky filled with stars'],
    ['sky-milky-way', '银河', 'milky way', 'visible Milky Way', 'the Milky Way visible across the sky'],
    ['sky-aurora', '极光', 'aurora', 'colorful aurora', 'a colorful aurora across the sky'],
    ['sky-eclipse', '日食', 'solar eclipse', 'dramatic solar eclipse', 'a dramatic solar eclipse'],
    ['sky-double-moon', '双月', 'two moons', 'two moons in the sky', 'two moons visible in the sky'],
    ['sky-meteor', '流星雨', 'meteor shower', 'bright meteor shower', 'a bright meteor shower crossing the sky'],
  ]),

  ...group('色彩', '综合色调', [
    ['tone-warm', '暖色调', 'warm color palette', 'warm color palette', 'a cohesive warm color palette'],
    ['tone-cool', '冷色调', 'cool color palette', 'cool color palette', 'a cohesive cool color palette'],
    ['tone-neutral', '中性色调', 'neutral colors', 'neutral color palette', 'a balanced neutral color palette'],
    ['tone-pastel', '粉彩色调', 'pastel colors', 'soft pastel palette', 'a soft pastel color palette'],
    ['tone-jewel', '宝石色调', 'jewel tones', 'rich jewel-tone palette', 'a rich jewel-tone color palette'],
    ['tone-earth', '大地色', 'earth tones', 'earth-tone palette', 'a natural earth-tone palette'],
    ['tone-neon', '霓虹色', 'neon colors', 'neon color palette', 'a vivid controlled neon palette'],
    ['tone-monochrome', '单色调', 'monochrome', 'monochromatic palette', 'a deliberate monochromatic palette'],
  ]),
  ...group('色彩', '配色关系', [
    ['scheme-complementary', '互补色', 'complementary colors', 'complementary color scheme', 'a balanced complementary color scheme'],
    ['scheme-analogous', '邻近色', 'analogous colors', 'analogous color scheme', 'a harmonious analogous color scheme'],
    ['scheme-triadic', '三角色', 'triadic colors', 'triadic color scheme', 'a balanced triadic color scheme'],
    ['scheme-split-complement', '分裂互补', 'split-complementary colors', 'split-complementary palette', 'a controlled split-complementary palette'],
    ['scheme-duotone', '双色调', 'duotone', 'duotone palette', 'a graphic duotone color treatment'],
    ['scheme-accent-color', '强调色', 'accent color', 'single accent color', 'one strong accent color against a restrained palette'],
    ['scheme-color-block', '色块搭配', 'color blocking', 'bold color blocking', 'bold clean color blocking'],
    ['scheme-gradient', '渐变配色', 'color gradient', 'smooth color gradient', 'a smooth controlled color gradient'],
  ]),
  ...group('色彩', '调色风格', [
    ['grade-cinematic-teal-orange', '青橙电影色', 'teal and orange', 'cinematic teal-and-orange grade', 'a cinematic teal-and-orange color grade'],
    ['grade-filmic', '胶片调色', 'filmic colors', 'filmic color grading', 'a refined filmic color grade'],
    ['grade-vintage', '复古调色', 'vintage colors', 'vintage color grading', 'a nostalgic vintage color grade'],
    ['grade-faded', '褪色质感', 'faded colors', 'soft faded color grade', 'a soft faded color treatment'],
    ['grade-crisp', '清透调色', 'crisp colors', 'clean crisp color grading', 'a clean and luminous color grade'],
    ['grade-dreamy', '梦幻调色', 'dreamy colors', 'dreamy color grading', 'a luminous dreamy color grade'],
    ['grade-dark-fantasy', '暗黑幻想色', 'dark fantasy colors', 'dark-fantasy color grade', 'a rich dark-fantasy color grade'],
    ['grade-chinese-aesthetic', '东方雅色', 'traditional Chinese colors', 'refined traditional Chinese palette', 'a refined traditional Chinese color palette'],
  ]),
  ...group('色彩', '明暗对比', [
    ['contrast-high-key', '高调明亮', 'high key', 'high-key lighting and color', 'a bright high-key tonal range'],
    ['contrast-low-key', '低调暗色', 'low key', 'low-key lighting and color', 'a dramatic low-key tonal range'],
    ['contrast-soft', '柔和对比', 'soft contrast', 'soft tonal contrast', 'soft controlled tonal contrast'],
    ['contrast-strong', '强烈对比', 'strong contrast', 'strong tonal contrast', 'strong deliberate tonal contrast'],
    ['contrast-silhouette', '剪影对比', 'silhouette contrast', 'strong silhouette contrast', 'strong contrast around the subject silhouette'],
    ['contrast-backlit', '逆光明暗', 'backlit contrast', 'dramatic backlit contrast', 'dramatic contrast created by backlighting'],
    ['contrast-shadow-color', '彩色阴影', 'colored shadows', 'colored shadow design', 'purposeful colored shadows'],
    ['contrast-luminous-dark', '暗底发光', 'luminous on dark', 'luminous subject against dark background', 'a luminous subject against a dark background'],
  ]),

  ...group('特效', '粒子效果', [
    ['fx-sparkles', '闪光粒子', 'sparkles', 'subtle sparkle particles', 'subtle sparkling particles'],
    ['fx-embers', '飞散火星', 'embers', 'floating embers', 'glowing embers floating through the air'],
    ['fx-petals', '花瓣飘落', 'falling petals', 'falling flower petals', 'flower petals drifting through the scene'],
    ['fx-feathers', '羽毛飘落', 'floating feathers', 'floating feathers', 'soft feathers floating in the air'],
    ['fx-dust-motes', '尘埃微粒', 'dust motes', 'visible dust motes', 'tiny dust motes visible in the light'],
    ['fx-snow-particles', '细雪粒子', 'snow particles', 'fine snow particles', 'fine snow particles drifting in the air'],
    ['fx-energy-particles', '能量粒子', 'energy particles', 'glowing energy particles', 'glowing magical energy particles'],
    ['fx-fireflies', '萤火虫', 'fireflies', 'glowing fireflies', 'small glowing fireflies'],
  ]),
  ...group('特效', '环境效果', [
    ['fx-mist-layer', '薄雾层', 'mist', 'layered ground mist', 'a thin layer of ground mist'],
    ['fx-smoke-plume', '烟雾', 'smoke', 'volumetric smoke plume', 'a controlled plume of volumetric smoke'],
    ['fx-rain-streak', '雨丝', 'rain streaks', 'visible rain streaks', 'visible streaks of falling rain'],
    ['fx-water-splash', '水花飞溅', 'water splash', 'dynamic water splashes', 'dynamic water splashing through the scene'],
    ['fx-debris', '碎屑飞散', 'flying debris', 'flying environmental debris', 'small debris flying through the air'],
    ['fx-leaves', '落叶飞舞', 'flying leaves', 'windblown leaves', 'leaves carried by the wind'],
    ['fx-heat-haze', '热浪扭曲', 'heat haze', 'subtle heat distortion', 'subtle heat-haze distortion'],
    ['fx-frost', '冰霜蔓延', 'frost', 'spreading frost effect', 'frost spreading across nearby surfaces'],
  ]),
  ...group('特效', '动态表现', [
    ['fx-motion-lines', '速度线', 'speed lines', 'controlled speed lines', 'controlled graphic speed lines'],
    ['fx-motion-blur', '运动模糊', 'motion blur', 'directional motion blur', 'directional motion blur emphasizing movement'],
    ['fx-afterimage', '残影', 'afterimage', 'stylized motion afterimage', 'a stylized motion afterimage'],
    ['fx-impact-frame', '冲击画面', 'impact effect', 'strong impact effect', 'a strong visual impact effect'],
    ['fx-shockwave', '冲击波', 'shockwave', 'expanding shockwave', 'an expanding circular shockwave'],
    ['fx-cloth-motion', '衣摆飞扬', 'flowing clothes', 'dramatically flowing fabric', 'fabric flowing dramatically with the motion'],
    ['fx-hair-motion', '发丝飞扬', 'flowing hair', 'wind-swept flowing hair', 'hair flowing dynamically in the wind'],
    ['fx-weapon-trail', '武器轨迹', 'weapon trail', 'luminous weapon trail', 'a luminous trail following the weapon movement'],
  ]),
  ...group('特效', '镜头视觉', [
    ['fx-lens-flare', '镜头光晕', 'lens flare', 'controlled lens flare', 'a controlled cinematic lens flare'],
    ['fx-bloom', '柔光溢出', 'bloom', 'subtle bloom effect', 'a subtle luminous bloom effect'],
    ['fx-bokeh', '散景光斑', 'bokeh', 'cinematic bokeh lights', 'cinematic out-of-focus bokeh lights'],
    ['fx-vignette', '暗角', 'vignette', 'subtle vignette', 'a subtle vignette around the frame'],
    ['fx-light-leak', '漏光', 'light leak', 'filmic light leak', 'a soft filmic light-leak effect'],
    ['fx-prism', '棱镜折射', 'prismatic refraction', 'prismatic light refraction', 'subtle prismatic light refraction'],
    ['fx-glitch', '故障艺术', 'glitch effect', 'controlled digital glitch', 'a controlled digital glitch effect'],
    ['fx-hologram', '全息效果', 'holographic effect', 'holographic projection effect', 'a luminous holographic projection effect'],
  ]),

  ...group('画风', '真实摄影', [
    ['style-photo-photoreal', '真实照片', 'photorealistic photo', 'highly photorealistic photography', 'a convincing true-to-life photograph', ['照片感', '写实照片', 'photorealistic']],
    ['style-photo-documentary', '纪实摄影', 'documentary photo', 'documentary photography', 'an honest observational documentary photograph', ['纪实', 'documentary']],
    ['style-photo-candid', '生活抓拍', 'candid photo', 'natural candid photography', 'a spontaneous candid photograph from everyday life', ['抓拍', '生活照', 'candid']],
    ['style-photo-commercial-portrait', '商业人像', 'commercial portrait photo', 'polished commercial portrait photography', 'a polished commercial portrait photograph', ['广告人像', 'commercial portrait']],
    ['style-photo-fashion-editorial', '时尚人像', 'fashion editorial photo', 'fashion editorial portrait photography', 'a refined fashion-editorial portrait photograph', ['时尚摄影', 'fashion editorial']],
    ['style-photo-studio-portrait', '棚拍人像', 'studio portrait photo', 'professional studio portrait photography', 'a professionally lit studio portrait photograph', ['影棚人像', 'studio portrait']],
    ['style-photo-environmental-portrait', '环境人像', 'environmental portrait photo', 'environmental portrait photography', 'a true-to-life environmental portrait showing the subject in context', ['场景人像', 'environmental portrait']],
    ['style-photo-street', '街头摄影', 'street photo', 'observational street photography', 'an unposed observational street photograph', ['街拍', 'street photography']],
    ['style-photo-film-still', '电影剧照', 'live-action film still', 'cinematic live-action film still', 'a cinematic still from a live-action film', ['真人电影感', 'live action']],
    ['style-photo-photojournalism', '新闻摄影', 'photojournalism', 'authentic photojournalistic photography', 'an authentic photojournalistic photograph', ['新闻照片', 'photojournalistic']],
    ['style-photo-smartphone', '手机摄影', 'smartphone photo', 'natural smartphone photography', 'a believable photograph taken with a modern smartphone', ['随手拍', '手机照片', 'smartphone']],
    ['style-photo-analog-portrait', '胶片人像', 'analog film portrait', 'analog film portrait photography', 'a natural portrait captured on analog film', ['胶卷人像', 'film portrait']],
  ]),
  ...group('质量渲染', '真实细节', [
    ['detail-real-skin-texture', '自然皮肤纹理', 'natural skin texture', 'natural unretouched skin texture', 'natural unretouched skin texture without plastic smoothing', ['真实皮肤', '皮肤纹理']],
    ['detail-real-pores-lines', '毛孔与细纹', 'visible pores, subtle fine lines', 'visible skin pores and subtle fine lines', 'visible pores and subtle fine lines at a believable scale', ['毛孔', '细纹']],
    ['detail-real-skin-tone', '自然肤色过渡', 'natural skin tone variation', 'natural skin-tone variation and color transitions', 'natural variation and transitions across the skin tone', ['肤色过渡', '真实肤色']],
    ['detail-real-hair', '真实发丝', 'realistic individual hair strands', 'realistic individual hair strands and flyaways', 'individual hair strands and a few natural flyaways', ['自然发丝', '发丝']],
    ['detail-real-eyes', '真实眼睛', 'realistic eyes, natural catchlights', 'realistic eyes with natural catchlights and moist reflections', 'realistic eyes with restrained natural catchlights and moist reflections', ['自然眼睛', '眼神光']],
    ['detail-real-fabric', '真实布料', 'realistic fabric weave and folds', 'physically believable fabric weave and folds', 'fabric with a believable weave, weight, and natural folds', ['布料纹理', '衣料']],
    ['detail-real-materials', '真实材质', 'physically believable materials', 'physically believable material response', 'materials reacting believably to light according to their surfaces', ['材质真实', '物理材质']],
    ['detail-real-imperfections', '自然小瑕疵', 'subtle natural imperfections', 'subtle natural imperfections, no beauty filter', 'subtle natural imperfections without a heavy beauty filter', ['去美颜', '自然瑕疵']],
    ['detail-real-proportions', '真实人体比例', 'true-to-life human proportions', 'anatomically plausible true-to-life human proportions', 'anatomically plausible human proportions without stylized exaggeration', ['真人比例', '自然比例']],
    ['detail-real-lighting', '真实光影', 'physically plausible light and shadows', 'physically plausible lighting, contact shadows, and reflections', 'light, contact shadows, and reflections that behave naturally', ['自然光影', '物理光照']],
  ]),
];
